config/routes.rb
Emerald::Application.routes.draw do
  resources :articles

  resources :words

  devise_for :users

  root :to => 'home#index'
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Article < ActiveRecord::Base
  attr_accessible :content
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/word.rb
# == Schema Information
#
# Table name: words
#
#  id         :integer          not null, primary key
#  right      :string(255)
#  wrong      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Word < ActiveRecord::Base
  attr_accessible :right, :wrong
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
# coding: utf-8

class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @result = session[:result]
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])

    if @article.save
      @words = Word.all.map{|w| w.right}
      session[:result] = spelling_check(@article.content, @words)

      redirect_to @article, notice: 'Article was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update_attributes(params[:article])
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_url
  end

  private

  def spelling_check(article, words)
    [{:pos=>5, :origin=>"赵净波", :maybe=>"赵静波"}]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.all
  end

  def show
    @word = Word.find(params[:id])
  end

  def new
    @word = Word.new
  end

  def edit
    @word = Word.find(params[:id])
  end

  def create
    @word = Word.new(params[:word])

    if @word.save
      redirect_to @word, notice: 'Word was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @word = Word.find(params[:id])

    if @word.update_attributes(params[:word])
      redirect_to @word, notice: 'Word was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    redirect_to words_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def format_highlight(content, result)
    output = ""
    last_pos = 0
    result.each do |r|
      output += content[0...r[:pos]] + "<span class='highlight-word'>#{r[:origin]}</span>"
      last_pos += r[:pos] + r[:origin].size
    end
    output += content[last_pos...content.size]
    return output
  end

  def format_advise(result)
    output = ""
    result.each do |r|
      output += r[:origin] + " -> " + r[:maybe] + "<br>"
    end
    return output
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/articles/_form.html.haml
= form_for @article, :html=>{:role=>"form"} do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    .col-md-8.col-md-offset-1
      = f.label "输入文字", :class=>"col-md-2 control-label"
      = f.text_area :content, :rows=>12, :class=>"form-control"

  .form-group
    .col-md-8.col-md-offset-1
      = f.submit '提交', :class=>"btn btn-success"
      = link_to '重置', root_path, :class=>"btn btn-default"

app/views/articles/edit.html.haml
%h2 编辑文章

= render 'form'

app/views/articles/index.html.haml
%h2 全部文章

.row
  .col-md-9
    %table.table.table-hover
      %tr
        %th 内容
        %th
        %th
        %th
    
      - @articles.each do |article|
        %tr
          %td= article.content
          %td= link_to 'Show', article, :class=>"btn btn-default"
          %td= link_to 'Edit', edit_article_path(article), :class=>"btn btn-primary"
          %td= link_to 'Destroy', article, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-danger"

= link_to '新建文章', new_article_path, :class=>"btn btn-info"

app/views/articles/new.html.haml
%h2 新建文章

= render 'form'

app/views/articles/show.html.haml
%h2 纠错结果

= form_for @article, :html=>{:role=>"form"} do |f|
  .form-group
    .col-md-8.col-md-offset-1
      = f.label "纠错结果", :class=>"col-md-2 control-label"
      .input-block
        = format_highlight(@article.content, @result).html_safe

  .form-group
    .col-md-8.col-md-offset-1
      = f.label "纠错建议", :class=>"col-md-2 control-label"
      .advise-block
        = format_advise(@result).html_safe

  .form-group
    .col-md-8.col-md-offset-1
      = link_to '编辑', edit_article_path(@article), :class=>"btn btn-primary"
      = link_to '返回', articles_path, :class=>"btn btn-default"

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/_flash_messages.html.haml
- if flash and flash.any?
  - flash.each do |key, value|
    - if :success == key
      .alert.alert-success.alert-dismissable
        %button{:type=>"button", :class=>"close", "data-dismiss"=>"alert", "aria-hidden"=>"true"}= "&times;".html_safe
        = value
    - elsif :error == key
      .alert.alert-danger.alert-dismissable
        %button{:type=>"button", :class=>"close", "data-dismiss"=>"alert", "aria-hidden"=>"true"}= "&times;".html_safe
        = value
    - else
      .alert.alert-info.alert-dismissable
        %button{:type=>"button", :class=>"close", "data-dismiss"=>"alert", "aria-hidden"=>"true"}= "&times;".html_safe
        = value

app/views/layouts/_navbar_top.html.haml
.navbar-header
  %button.navbar-toggle.collapsed{:type=>"button", "data-toggle"=>"collapse", "data-target"=>".navbar-collapse"}
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
  = link_to "官方网站", root_path, :class=>"navbar-brand"
.collapse.navbar-collapse
  %ul.nav.navbar-nav
    %li{:class => (controller_name=="home"?"active":nil)}= link_to "首页", root_path
    %li{:class => (controller_name=="articles"?"active":nil)}= link_to "拼写纠错", articles_path
    %li{:class => (controller_name=="words"?"active":nil)}= link_to "词语管理", words_path
  %ul.nav.navbar-nav.navbar-right
    - if user_signed_in?
      %li.dropdown
        %a{"data-toggle"=>"dropdown", :href=>"#"}
          = "欢迎您，#{current_user.email}"
          %b.caret
        %ul.dropdown-menu{:role=>"menu", "aria-labelledby"=>"label"}
          %li{:role=>"presentation"}
            %a{:role=>"menuitem", :tabindex=>"-1", :href=>root_path} 个人主页
          %li{:role=>"presentation"}
            %a{:role=>"menuitem", :tabindex=>"-1", :href=>destroy_user_session_path, "data-method"=>"delete"} 退出登录
    - else
      %li= link_to "注册", new_user_registration_path
      %li= link_to "登录", new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html{:lang=>"zh-cn"}
  %head
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    %title= "#{yield(:title)}"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body

    .navbar.navbar-inverse.navbar-fixed-top{:role=>"navigation"}
      .container
        = render "layouts/navbar_top"

    .container
      = render "layouts/flash_messages"
      = yield

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/words/_form.html.haml
= form_for @word, :html=>{:class=>"form-horizontal"} do |f|
  - if @word.errors.any?
    #error_explanation
      %h2= "#{pluralize(@word.errors.count, "error")} prohibited this word from being saved:"
      %ul
        - @word.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label "正确词语", :class=>"col-md-2 control-label"
    .col-md-3
      = f.text_field :right, :class=>"form-control"

  .form-group
    = f.label "错误词语", :class=>"col-md-2 control-label"
    .col-md-3
      = f.text_field :wrong, :class=>"form-control"

  .form-group
    .col-md-3.col-md-offset-2
      = f.submit '保存', :class=>"btn btn-success"
      = link_to '返回', words_path, :class=>"btn btn-default"

app/views/words/edit.html.haml
%h2 编辑词语

= render 'form'

app/views/words/index.html.haml
%h2 全部词语

.row
  .col-md-9
    %table.table.table-hover
      %tr
        %th 正确词语
        %th 错误词语
        %th
        %th
        %th
    
      - @words.each do |word|
        %tr
          %td= word.right
          %td= word.wrong
          %td= link_to '查看', word, :class=>"btn btn-default"
          %td= link_to '编辑', edit_word_path(word), :class=>"btn btn-primary"
          %td= link_to '删除', word, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-danger"

= link_to '新建词语', new_word_path, :class=>"btn btn-info"

app/views/words/new.html.haml
%h2 新建词语

= render 'form'

app/views/words/show.html.haml
%h2 查看词语

= form_for @word, :html=>{:class=>"form-horizontal"} do |f|
  .form-group
    = f.label "正确词语", :class=>"col-md-2 control-label"
    .col-md-3
      %p.form-control-static= @word.right

  .form-group
    = f.label "错误词语", :class=>"col-md-2 control-label"
    .col-md-3
      %p.form-control-static= @word.wrong

  .form-group
    .col-md-3.col-md-offset-2
      = link_to '编辑', edit_word_path(@word), :class=>"btn btn-primary"
      = link_to '返回', words_path, :class=>"btn btn-default"